import { NavItems } from '@/types'
import Head from 'next/head'
import { ReactNode, useRef } from 'react'
import Navbar from '../Navbar'
import SpaceBackground from '../SpaceBackground'

type Props = {
  children: ReactNode
}
export default function MainLayout({ children }: Props) {
  const scrollContainerRef = useRef<HTMLDivElement>(null)

  return (
    <>
      <Head>
        <title>arel.dev | Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="overflow-hidden">
        <div className="fixed inset-0">
          <SpaceBackground scrollContainerRef={scrollContainerRef} />
        </div>
        <div
          className="relative z-10 h-screen w-screen snap-y snap-mandatory overflow-scroll"
          ref={scrollContainerRef}
        >
          {children}
        </div>
      </div>
    </>
  )
}
