import Head from 'next/head'

type Props = {}

export default function Home({}: Props) {
  const a = ''
  return (
    <>
      <Head>
        <title>arel.dev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center justify-center min-h-screen text-xl">
        arel
        <a className="text-blue-500" href="https://github.com/Arelera">
          .dev
        </a>
      </div>
    </>
  )
}
